USE vmforge;

CREATE TABLE IF NOT EXISTS isos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  url TEXT NOT NULL,
  checksum VARCHAR(128) NULL,
  local_path TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
